version: "3"
services:
  nagios:
    tty: true
    container_name: ROCKY-NAGIOS
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:80"
    command: "/bin/bash"

